### PR TITLE
new: GTW advertisement

### PR DESCRIPTION
**Pull request by Anubhav652**
This is a simply resource made by me to advertise. Use /advert, /ad, /advertise. Syntax: /command msg. It costs 500$ but can be changed in settings.lua. I will also soon work on anti-spam system of this chat. This is useful if you want to trade for eg :- Finding someone to join my group.etc  / this group is hiring.
Basically for hiring purposes

### CODE REVIEW

**Comment by paa93** [comment]
Looks good, although there's a few small details in the layout I would like you to change for next release:
1. Include the header code with all the urls from GTWantispam and replace my name with your name. (I'll do this later if you don't as it's gonna be updated on all resources soon)
2. local function names are written like this: local_function and exported: exportedFunction

More info can be found in the contributions file in <root>, your resource is accepted for inclusion and you will soon receive an invitation to 404rq devs.

**Comment by willie-the-walrus** [comment]
I'd suggest adding this into the core as: "_advert(ising).lua_" in "_misc_", we should minimize the amount of resources (and files) to reduce the memory usage as much as possible.

**Comment by Anubhav652** [comment]
Ok, I'll work on this.

**Comment by paa93** [comment]
It's already moved, the version you committed broke the game mode by not using [ ] tags around the keyword "resources". Untested commits should be made to the development branch preferably.

**Comment by Anubhav652** [comment]
This is tested on my local server.

**Pull request merged**
