### PR TITLE
Cancel damage to outlaws by staff

### PR DESCRIPTION
**Pull request by Anubhav652**
Title.

### CODE REVIEW

**Comment by paa93** [comment]
We do have a solution in our local branch where bots spawns in staff team to prevent them from attacking staff at all. Seeing how players potentially could abuse this feature by attacking team mates it appears to be the right thing to do.

**Comment by Anubhav652** [comment]
You don't get my point. This is so that staffs cant shoot peds. I made 200K$ just by killing them and improved my whole weapon skill for a weapon. That was so easy in staff mode and I did not get any stars, even if I did, they were removed.

**Comment by paa93** [comment]
I'm not rejecting your commit, just saying that we need to merge it to stop all kinds of abuse.

**Comment by Anubhav652** [comment]
O

**Pull request merged**
