### PR TITLE
[update] Better way, using fetchRemote

### PR DESCRIPTION
**Pull request by Anubhav652**
No need of PHP files. Magic?

### CODE REVIEW

**Comment by paa93** [comment]
Have you tested on remote servers? MTA limit access to remote servers by default which is why PHP is used in the first place.

**Comment by Anubhav652** [comment]
remote servers?

**Comment by paa93** [comment]
Servers that is not localhost (127.0.0.1)

**Comment by Anubhav652** [comment]
Ok closed, doesn't work with remote servers.

**Pull request closed without merging**
